### ISSUE TITLE
axum_sever doesn't work with unreleased version of axum (0.3.0)

### ISSUE THREAD

**Issue by pbspbsingh** [programatik29/axum-server#24]
Lately Axum has modified the internal implementation of `Router` and they have started boxing the routers by default (https://github.com/tokio-rs/axum). Unfortunately these new changes don't work with `axum_server`.
I get following compilation error:
```
error[E0277]: `(dyn axum::clone_box_service::CloneService<axum::http::Request<axum::body::Body>, Response = axum::http::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::Bytes, axum::Error>>, Error = Infallible, Future = Pin<Box<(dyn futures_util::Future<Output = Result<axum::http::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::Bytes, axum::Error>>, Infallible>> + std::marker::Send + 'static)>>> + std::marker::Send + 'static)` cannot be shared between threads safely
```

**Comment by programatik29** [comment]
See #23.

**Comment by programatik29** [comment]
Keep this issue open until resolved. :+1:

**Comment by pbspbsingh** [comment]
Thanks for the prompt response.

**Comment by programatik29** [comment]
Updated yesterday. Version `0.3` works with `axum`.
